[package]
name = "nns-sub-utility"
version = "0.2.0"
description = "Subscriptions utility managed by the NNS"
repository = "https://github.com/icdevsorg/nns-sub-utility"
keywords = [ "subscriptions" ]
license = "MIT"

[dependencies]
base = "0.12.1"
timer-tool = "0.0.3"
sha2 = "0.1.0"
candy = "0.3.0"
rep-indy-hash = "0.1.1"
icrc3-mo = "0.2.6"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
icrc79-mo = "0.2.2"
vector = "0.2.0"
